### ISSUE TITLE
HA drops error while setting up the platform from the dev branch

### ISSUE THREAD

**Issue by DenielTorres** [kayjei/adax_wifi#8]
hi there! 

First of all awesome work with the Adax integration, it was a long-awaited integration for me! 

Although when trying to set up multiple zones (devices), HA gives me an error message with the following details: 

`Error while setting up platform adax_wifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adax_wifi/climate.py", line 43, in setup_platform
    for zone in devices_json[1]:
KeyError: 1` 

Does it mean anything to you? Thanks in advance for taking a look at it for me.
Cheers

**Comment by DenielTorres** [comment]
Sorry for the closing and re-opening the issue! It doesn't work, unfortunately. I found a closed issue with the same error message, but after rechecking the URLs 3 times, I'm not sure what's going on. Thanks!

**Comment by DenielTorres** [comment]
I just tried with the master branch and getting a different error: `DEBUG (SyncWorker_16) [custom_components.adax_wifi.climate] Response: {'errorTypeId': 10001}`

**Comment by kayjei** [comment]
@DenielTorres , sorry for my late reply.
 ´´´{'errorTypeId': 10001}´´´ is the error code for wrong username/password. In this case that means that the signature does not match the URL or any of the attributes is faulty. Probably, also ´´´devices_json[1]: KeyError: 1´´´ is the same, since the Key 1 will be missing in a faulty attempt.
Please verify that all attributes match your fetched values.
